name: Nginx proxy manager images CI

on:
  workflow_dispatch:

env:
  IMAGE_NAME: carlesbarreda/nginx-proxy-manager

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint docker/Dockerfile
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: docker/Dockerfile

      - name: Lint docker/dev/Dockerfile
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: docker/dev/Dockerfile

  scanner:
    name: Build and scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Get npm version
        #TODO: some file content check 
        run: echo "NPM_VERSION=$(cat .version)" >> $GITHUB_ENV

      - name: Build npm
        run: |
          cd scripts
          ./frontend-build
          ./buildx \
            --tag $IMAGE_NAME:$NPM_VERSION \
            --tag $IMAGE_NAME:latest \
            --progress=plain \
            --no-cache \
            --push

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ env.NPM_VERSION }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  Build:
    name: "Nginx proxy manager"
    runs-on: ubuntu-20.04
    needs: [lint, scanner]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get npm version
        #TODO: some file content check 
        run: echo "NPM_VERSION=$(cat .version)" >> $GITHUB_ENV

      - name: Build npm
        run: |
          cd scripts
          ./frontend-build
          ./buildx \
            --tag $IMAGE_NAME:$NPM_VERSION \
            --tag $IMAGE_NAME:latest \
            --progress=plain \
            --no-cache \
            --push
